version: '3'

services:
  hiberus:
    build: ./hiberus-back
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://seo_bdd:3306/seohistory?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 
      API_KEY: 
    restart: always
    depends_on:
      seo_bdd:
          condition: service_healthy
          
  seo_bdd:
    image: mysql:8.0.32 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: seohistory
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  frontend:
    build:
      context: ./hiberus-front
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - hiberus
